[settings]
experimental = true
lockfile = true

[tools]
go = "latest"
"ubi:vektra/mockery" = "latest"

[tasks.build]
description = "Compile the server."
run = "go build -o /tmp/codecrafters-build-redis-go ."
sources = ["go.mod", "go.sum", "**/*.go"]
outputs = { auto = true }
alias = "b"

[tasks.spawn]
description = "Run the server locally."
run = "/tmp/codecrafters-build-redis-go"
depends = "build"
alias = "s"
quiet = true

[tasks.mocks]
description = "Run the Mockery mock generation tool."
run = "mockery"
sources = ["go.mod", "go.sum", "**/*.go", ".mockery-yml"]
outputs = { auto = true }
alias = "m"

[tasks.test]
description = "Run the unit tests."
run = "go test -shuffle=on -race -cover -timeout=15s ./..."
depends = ["build", "mocks"]
sources = ["go.mod", "go.sum", "**/*.go"]
outputs = { auto = true }
alias = "t"

[tasks.integration-test]
description = "Run the integration tests."
run = "go test -shuffle=on -race -cover -timeout=30s -count=1 -tags=integration -v ./integration"
depends = "build"
wait_for = "test"
alias = "i"

[tasks.check]
description = "Run all tests."
depends = ["test", "integration-test"]
alias = "c"
