[hooks]
enter = "mise i -q"

[settings]
experimental = true
lockfile = true
status.missing_tools = "always"
status.show_env = true
status.show_tools = true

[tools]
go = "latest"
cosign = "latest"
usage = "latest"

[tasks.build]
description = "Compile the server."
run = "go build -o /tmp/codecrafters-build-redis-go ."
sources = ["go.mod", "go.sum", "**/*.go"]
outputs = { auto = true }
alias = "b"

[tasks.spawn]
description = "Run the server locally."
run = "/tmp/codecrafters-build-redis-go"
depends = "build"
alias = "s"
quiet = true

[tasks.test]
description = "Run the unit tests."
run = "go test -shuffle=on -race -cover -timeout=15s $(go list ./... | grep -v integration)"
depends = "build"
sources = ["go.mod", "go.sum", "**/*.go"]
outputs = { auto = true }
alias = "t"

[tasks.test-rerun]
description = "Run the unit tests, even if no changes have been made."
run = "go test -shuffle=on -race -cover -timeout=15s $(go list ./... | grep -v integration)"
depends = "build"
sources = ["go.mod", "go.sum", "**/*.go"]
alias = "tr"

[tasks.integration-test]
description = "Run the integration tests."
run = "go test -shuffle=on -race -cover -timeout=30s -count=1 ./integration"
depends = "build"
wait_for = "test"
alias = "i"

[tasks.check]
description = "Run all tests."
depends = ["test", "integration-test"]
alias = "c"
