// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: matryer

package redis_test

import (
	"sync"

	"github.com/codecrafters-io/redis-starter-go/redis"
)

// Ensure that MockHandler does implement redis.Handler.
// If this is not the case, regenerate this file with mockery.
var _ redis.Handler = &MockHandler{}

// MockHandler is a mock implementation of redis.Handler.
//
//	func TestSomethingThatUsesHandler(t *testing.T) {
//
//		// make and configure a mocked redis.Handler
//		mockedHandler := &MockHandler{
//			CommandFunc: func() string {
//				panic("mock out the Command method")
//			},
//			HandleFunc: func(args redis.Array[redis.BulkString]) redis.Value {
//				panic("mock out the Handle method")
//			},
//		}
//
//		// use mockedHandler in code that requires redis.Handler
//		// and then make assertions.
//
//	}
type MockHandler struct {
	// CommandFunc mocks the Command method.
	CommandFunc func() string

	// HandleFunc mocks the Handle method.
	HandleFunc func(args redis.Array[redis.BulkString]) redis.Value

	// calls tracks calls to the methods.
	calls struct {
		// Command holds details about calls to the Command method.
		Command []struct {
		}
		// Handle holds details about calls to the Handle method.
		Handle []struct {
			// Args is the args argument value.
			Args redis.Array[redis.BulkString]
		}
	}
	lockCommand sync.RWMutex
	lockHandle  sync.RWMutex
}

// Command calls CommandFunc.
func (mock *MockHandler) Command() string {
	if mock.CommandFunc == nil {
		panic("MockHandler.CommandFunc: method is nil but Handler.Command was just called")
	}
	callInfo := struct {
	}{}
	mock.lockCommand.Lock()
	mock.calls.Command = append(mock.calls.Command, callInfo)
	mock.lockCommand.Unlock()
	return mock.CommandFunc()
}

// CommandCalls gets all the calls that were made to Command.
// Check the length with:
//
//	len(mockedHandler.CommandCalls())
func (mock *MockHandler) CommandCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockCommand.RLock()
	calls = mock.calls.Command
	mock.lockCommand.RUnlock()
	return calls
}

// Handle calls HandleFunc.
func (mock *MockHandler) Handle(args redis.Array[redis.BulkString]) redis.Value {
	if mock.HandleFunc == nil {
		panic("MockHandler.HandleFunc: method is nil but Handler.Handle was just called")
	}
	callInfo := struct {
		Args redis.Array[redis.BulkString]
	}{
		Args: args,
	}
	mock.lockHandle.Lock()
	mock.calls.Handle = append(mock.calls.Handle, callInfo)
	mock.lockHandle.Unlock()
	return mock.HandleFunc(args)
}

// HandleCalls gets all the calls that were made to Handle.
// Check the length with:
//
//	len(mockedHandler.HandleCalls())
func (mock *MockHandler) HandleCalls() []struct {
	Args redis.Array[redis.BulkString]
} {
	var calls []struct {
		Args redis.Array[redis.BulkString]
	}
	mock.lockHandle.RLock()
	calls = mock.calls.Handle
	mock.lockHandle.RUnlock()
	return calls
}
